openapi: "3.0.0"
info:
  description: "読書記録Webアプリのバックエンド。"
  version: "0.1.0"
  title: "Book Record Backend"
  contact:
    email: "hiyoko3m.tech@gmail.com"
servers:
- url: "http://localhost:8000/v1"
  description: "For local development"
tags:
- name: "user"
  description: "ユーザ操作"
- name: "book"
  description: "本のCRUD系API"
- name: "record"
  description: "読書記録のCRUD系API"
security:
- accessTokenBearer: []
paths:
  /login-session:
    post:
      tags:
      - "user"
      summary: "IdPに送信するnonceやcode_challengeの発行"
      operationId: "issueNonce"
      responses:
        "200":
          description: "ログインセッション開始"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  session_id:
                    type: "string"
                  nonce:
                    type: "string"
                    example: "abcde1234"
                  code_challenge:
                    type: "string"
                    example: "XYZ789"
      security: []
  /login:
    post:
      tags:
      - "user"
      summary: "ログイン"
      description: "IdPの発行したone-time codeを使ってシステムにログインする。内部でIdPにアクセスしてIDトークンを発行してもらうことでユーザ認証を行う"
      operationId: "login"
      requestBody:
        description: "One-time authorization code for IdP"
        content:
          application/json:
            schema:
              type: "object"
              properties:
                session_id:
                  type: "string"
                code:
                  type: "string"
      responses:
        "200":
          description: "ログイン成功。Access tokenを返す"
          headers:
            Set-Cookie:
              schema:
                type: string
                example: refresh_token=abcde12345; Path=/; HttpOnly; Secure
          content:
            application/json:
              schema:
                type: string
        "400":
          description: "ユーザが存在しない。ユーザ作成のためのone-time codeを返す"
          content:
            application/json:
              schema:
                type: string
        "403":
          description:
            "IDトークンが不正"
      security: []
  /signup:
    post:
      tags:
      - "user"
      summary: "サインアップ"
      description: "/loginから発行されたサインアップ用codeを使い、サインアップを行う"
      operationId: "signUp"
      requestBody:
        description: "ユーザ情報"
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                code:
                  type: "string"
                user:
                  $ref: "#/components/schemas/User"
      responses:
        200:
          description: "ユーザ作成に成功。Access tokenを返す"
          headers:
            Set-Cookie:
              schema:
                type: string
                example: refresh_token=abcde12345; Path=/; HttpOnly; Secure
          content:
            application/json:
              schema:
                type: string
        400:
          description:
            "ユーザ作成に失敗"
        403:
          description:
            "サインアップ用codeが不正"
      security: []
  /token:
    post:
      tags:
      - "user"
      summary: "Refresh tokenを元にaccess tokenを発行する。Refresh tokenも新しくする"
      operationId: "refreshToken"
      responses:
        "200":
          description: "Access tokenを発行"
          headers:
            Set-Cookie:
              schema:
                type: string
                example: refresh_token=abcde12345; Path=/; HttpOnly; Secure
          content:
            application/json:
              schema:
                type: string
        403:
          description:
            "Refresh tokenが不正、あるいは期限切れ"

      security:
        - refreshTokenCookie: []
  /books:
    get:
      tags:
      - "book"
      summary: "登録された本の一覧取得"
      description:
        "idの昇順に本の一覧を返す"
      operationId: "listBooks"
      responses:
        "200":
          description: "成功時"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  books:
                    type: "array"
                    items:
                      $ref: "#/components/schemas/Book"
  /book:
    post:
      tags:
      - "book"
      summary: "新しい本の登録"
      operationId: "createBook"
      requestBody:
        description: "登録する本のオブジェクト"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BookSent"
      responses:
        "200":
          description: "成功時"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  book_id:
                    type: "integer"
        "422":
          description: "無効な入力"
  /book/{bookId}:
    get:
      tags:
      - "book"
      summary: "本の情報の詳細取得"
      operationId: "getBookById"
      parameters:
      - name: "bookId"
        in: "path"
        description: "本のID"
        required: true
        schema:
          type: "integer"
          format: "int32"
      responses:
        "200":
          description: "成功時"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  book:
                    $ref: "#/components/schemas/Book"
        "404":
          description: "存在しない本のID"
        "422":
          description: "無効な入力"
    post:
      tags:
      - "book"
      summary: "本の情報の更新"
      operationId: "updateBook"
      parameters:
      - name: "bookId"
        in: "path"
        description: "更新する本のID"
        required: true
        schema:
          type: "integer"
          format: "int32"
      requestBody:
        description: "登録する本のオブジェクト"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BookSent"
      responses:
        "200":
          description: "成功時"
        "404":
          description: "存在しない本のID"
        "422":
          description: "無効な入力"
    delete:
      tags:
      - "book"
      summary: "本の削除"
      operationId: "deleteBook"
      parameters:
      - name: "bookId"
        in: "path"
        description: "本のID"
        required: true
        schema:
          type: "integer"
          format: "int32"
      responses:
        "200":
          description: "成功時"
        "404":
          description: "存在しない本のID"
        "422":
          description: "無効な入力"
  /records:
    get:
      tags:
      - "record"
      summary: "読書記録の一覧取得"
      description: "条件に合う読書記録を全て表示する"
      operationId: "listRecords"
      parameters:
      - name: "userIds"
        in: "query"
        description: "表示対象のユーザID配列"
        schema:
          type: "array"
          items:
            type: "integer"
            format: "int32"
      - name: "bookIds"
        in: "query"
        description: "表示対象の本のID配列"
        schema:
          type: "array"
          items:
            type: "integer"
            format: "int32"
      - name: "sinceDatetime"
        in: "query"
        description: "この時刻以降の読書記録を表示する（等号を含む）"
        schema:
          type: "string"
          format: "date-time"
      - name: "untilDatetime"
        in: "query"
        description: "この時刻以前の読書記録を表示する（等号を含まない）"
        schema:
          type: "string"
          format: "date-time"
      responses:
        "200":
          description: "成功時"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  records:
                    type: "array"
                    items:
                      $ref: "#/components/schemas/Record"
  /record:
    post:
      tags:
      - "record"
      summary: "読書記録の新規登録"
      operationId: "createRecord"
      requestBody:
        description: "登録する読書記録情報"
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/RecordForm"
      responses:
        "200":
          description: "成功時"
        "422":
          description: "無効な入力"
  /record/{recordId}:
    get:
      tags:
      - "record"
      summary: "読書記録の詳細取得"
      operationId: "getRecord"
      parameters:
      - name: "recordId"
        in: "path"
        required: true
        description: "詳細表示する読書記録ID"
        schema:
          type: "integer"
          format: "int32"
      responses:
        "200":
          description: "成功時"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Record"
        "404":
          description: "存在しない読書記録ID"
        "422":
          description: "無効な入力"
    post:
      tags:
      - "record"
      summary: "読書記録のフォームからの更新"
      operationId: "udpateRecord"
      parameters:
      - name: "recordId"
        in: "path"
        required: true
        description: "変更する読書記録ID"
        schema:
          type: "integer"
          format: "int32"
      requestBody:
        description: "変更する読書記録情報"
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/RecordForm"
      responses:
        "200":
          description: "成功時"
        "404":
          description: "存在しない読書記録ID"
        "422":
          description: "無効な入力"
    delete:
      tags:
      - "record"
      summary: "読書記録の削除"
      operationId: "deleteRecord"
      parameters:
      - name: "recordId"
        in: "path"
        required: true
        description: "削除する読書記録ID"
        schema:
          type: "integer"
          format: "int32"
      responses:
        "200":
          description: "成功時"
        "404":
          description: "存在しない本のID"
        "422":
          description: "無効な入力"
components:
  securitySchemes:
    refreshTokenCookie:
      type: apiKey
      in: cookie
      name: refresh_token
    accessTokenBearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: "object"
      required:
      - "username"
      properties:
        username:
          type: "string"
    Book:
      type: "object"
      required:
      - "title"
      properties:
        id:
          type: "integer"
          format: "int32"
        title:
          type: "string"
    BookSent:
      type: "object"
      required:
      - "title"
      properties:
        title:
          type: "string"
    RecordForm:
      type: "object"
      required:
      - "bookId"
      - "startPage"
      - "endPage"
      properties:
        bookId:
          description: "読んだ本のID"
          type: "integer"
          format: "int32"
        startPage:
          description: "開始ページ"
          type: "integer"
          format: "int32"
        endPage:
          description: "終了ページ"
          type: "integer"
          format: "int32"
        comment:
          description: "備考・コメント"
          type: "string"
    Record:
      type: "object"
      required:
      - "userId"
      - "bookId"
      - "startPage"
      - "endPage"
      - "registeredDatetime"
      properties:
        id:
          type: "integer"
          format: "int32"
        userId:
          description: "読書したユーザID"
          type: "integer"
          format: "int32"
        bookId:
          description: "読んだ本のID"
          type: "integer"
          format: "int32"
        startPage:
          description: "開始ページ"
          type: "integer"
          format: "int32"
        endPage:
          description: "終了ページ"
          type: "integer"
          format: "int32"
        registeredDatetime:
          description: "記録の登録日時"
          type: "string"
          format: "date-time"
        comment:
          description: "備考・コメント"
          type: "string"