services:
  app:
    image: book_record_backend
    container_name: book_record_backend
    profiles:
      - app
      - dep
    depends_on:
      - idp
      - postgres
      - redis
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      DATABASE_URL: postgres://book_record:book_record@postgres/book_record
      REDIS_URL: redis://:dummy@redis
      ID_PROVIDER_URL: http://idp:8001
      DEBUG:

  idp:
    image: idp_mock
    container_name: idp_mock_server
    profiles:
      - dep
    ports:
      - 8001:8001
    environment:
      PORT: 8001
      RSA_PEM_FILE: /tmp/idp_mock/rsa_key.pem
    volumes:
      - ./../idp_mock/creds:/tmp/idp_mock

  postgres:
    image: postgres
    container_name: postgres
    profiles:
      - dep
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: book_record
      POSTGRES_PASSWORD: book_record
      POSTGRES_DB: book_record
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./.pgmount:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    profiles:
      - dep
    ports:
      - 6379:6379
    command: redis-server --requirepass dummy
    environment:
      - TZ=Asia/Tokyo
