services:
  postgres:
    image: postgres
    container_name: postgres
    profiles:
      - dep
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hyo
      POSTGRES_PASSWORD: hyo
      POSTGRES_DB: book_record
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgmount:/var/lib/postgresql/data

        #  redis:
        #    image: redis:alpine
        #    ports:
        #    - "6379:6379"
        #    command: redis-server --requirepass dummy
        #    environment:
        #    - TZ=Asia/Tokyo
